export const baseURL:string="http://localhost:8080/"
export const registerUserAPI:string= baseURL+"api/v1/register"
export const getUserByEmail:string= baseURL+"api/v1/profile"
export const getUserLogin:string= baseURL+"api/v1/login"
export const getUserProfile:string= baseURL+"api/v1/account"
export const getListProjects:string= baseURL+"api/v1/projects"
export const uploadFile:string= baseURL+"api/v1/upload"
export const changePassword:string= baseURL+"api/v1/change/password"
